addinf pm2 full path

diff --git a/.github/workflows/front-development.yaml b/.github/workflows/front-development.yaml
--- a/.github/workflows/front-development.yaml
+++ b/.github/workflows/front-development.yaml
@@ -44,13 +44,18 @@ jobs:
       - name: starting, or restarting the cms
         run: |
           cd /var/www/socar-cms/
+
+      - name: starting, or restarting the cms
+        run: |
+          cd /var/www/socar-cms/
           npm install || { echo "npm install failed"; exit 1; }
-          if pm2 list | grep -q "socar-cms-development"; then
+          # Check if the process is running
+          if /home/runner/.nvm/versions/node/v18.17.0/bin/pm2 list | grep -q "socar-cms-development"; then
             echo "socar-cms-development is running, trying restart"
-            /home/runner/.nvm/versions/node/v18.17.0/bin/pm2 restart socar-cms-development
+            /home/runner/.nvm/versions/node/v18.17.0/bin/pm2 restart socar-cms-development || { echo "Restart failed"; exit 1; }
           else
             echo "socar-cms-development is not running, starting now "
-            /home/runner/.nvm/versions/node/v18.17.0/bin/pm2 start npm --name "socar-cms-development" -- start -- --port=3050
+            /home/runner/.nvm/versions/node/v18.17.0/bin/pm2 start npm --name "socar-cms-development" -- start -- --port=3050 || { echo "Start failed"; exit 1; }
           fi
           /home/runner/.nvm/versions/node/v18.17.0/bin/pm2 save
         shell: bash
